### ISSUE TITLE
カウンターアプリの問題案

### ISSUE THREAD

**Issue by chvmvd** [ut-code/utcode-starter#25]

**Comment by chvmvd** [comment]
案1

```html
<div id="counter-value">0</div>
<button id="minus-button" type="button">-</button>
<button id="plus-button" type="button">+</button>
```

```js
let counter = 0;

function incrementCounter() {
  counter = counter + 1;
  document.getElementById("counter-value").textContent = counter;
}

function decrementCounter() {
  counter = counter - 1;
  document.getElementById("counter-value").textContent = counter;
}

document.getElementById("plus-button").onclick = incrementCounter;

document.getElementById("minus-button").onclick = decrementCounter;
```

```css
#counter-value {
  font-size: 48px;
  text-align: center;
  width: 160px;
}

#minus-button {
  font-size: 24px;
  color: black;
  background-color: white;
  width: 80px;
  border: solid;
  border-color: lightgray;
  border-radius: 20px;
}

#plus-button {
  font-size: 24px;
  color: white;
  background-color: royalblue;
  width: 80px;
  border: solid;
  border-color: royalblue;
  border-radius: 20px;
}
```

<img width="179" alt="Screenshot 2024-06-29 at 13 36 37" src="https://github.com/ut-code/utcode-starter/assets/104971044/0bc287d2-0a5f-4099-b7d6-805905e0bbf2">

https://jsfiddle.net/r1wj0ozd/

**Comment by chvmvd** [comment]
border-colorが嫌なら、border: noneにするという方法もあるが、少し不自然だと思われるかも。

```css
#counter-value {
  font-size: 48px;
  text-align: center;
  width: 160px;
}

#minus-button {
  font-size: 24px;
  color: black;
  background-color: lightgray;
  width: 80px;
  border: none;
  border-radius: 20px;
}

#plus-button {
  font-size: 24px;
  color: white;
  background-color: royalblue;
  width: 80px;
  border: none;
  border-radius: 20px;
}
```

<img width="179" alt="Screenshot 2024-06-29 at 13 38 22" src="https://github.com/ut-code/utcode-starter/assets/104971044/a44a5ce7-4792-486c-ac7d-029233744a58">

https://jsfiddle.net/h4wnk8gf/
