### ISSUE TITLE
おみくじアプリの問題案

### ISSUE THREAD

**Issue by chvmvd** [ut-code/utcode-starter#26]

**Comment by chvmvd** [comment]
```html
<div id="result">結果</div>
<button id="omikuji-button" type="button">おみくじを引く</button>
```

```js
function omikuji() {
  let r = Math.random();
  if (r < 0.2) {
    document.getElementById("result").textContent = "大吉";
    document.getElementById("result").style.color = "red";
  } else if (r < 0.7) {
    document.getElementById("result").textContent = "吉";
    document.getElementById("result").style.color = "black";
  } else {
    document.getElementById("result").textContent = "凶";
    document.getElementById("result").style.color = "blue";
  }
}

document.getElementById("omikuji-button").onclick = omikuji;
```

```css
#result {
  font-size: 48px;
  font-family: serif;
  text-align: center;
  writing-mode: vertical-rl;
  width: 60px;
  height: 120px;
  border: double;
  box-shadow: 3px 3px 5px lightgray;
  margin: 10px 50px;
}

#omikuji-button {
  width: 160px;
  height: 36px;
}
```

<img width="184" alt="Screenshot 2024-06-29 at 13 51 49" src="https://github.com/ut-code/utcode-starter/assets/104971044/981c495d-ff48-4e98-bca7-e1f6c1df17fc">

https://jsfiddle.net/s65nxh40/

**Comment by chvmvd** [comment]
ちょっと長くなるけど、こういうのもありかもしれない。

```html
<div id="omikuji-container">
  <div id="omikuji-description">運勢</div>
  <div id="omikuji-result">結果</div>
</div>
<button id="omikuji-button" type="button">おみくじを引く</button>
```

```css
#omikuji-container {
  font-family: serif;
  text-align: center;
  width: 80px;
  height: 200px;
  margin: 20px;
  border: double;
  border-color: red;
  box-shadow: 4px 4px 8px lightgray;
}

#omikuji-description {
  height: 24px;
  font-size: 24px;
  color: red;
  margin: 8px;
}

#omikuji-result {
  height: 144px;
  font-size: 52px;
  writing-mode: vertical-rl;
  margin: 8px;
}

#omikuji-button {
  width: 128px;
  height: 36px;
}
```

```js
function omikuji() {
  let r = Math.random();
  if (r < 0.2) {
    document.getElementById("omikuji-result").textContent = "大吉";
    document.getElementById("omikuji-result").style.color = "red";
  } else if (r < 0.7) {
    document.getElementById("omikuji-result").textContent = "吉";
    document.getElementById("omikuji-result").style.color = "black";
  } else {
    document.getElementById("omikuji-result").textContent = "凶";
    document.getElementById("omikuji-result").style.color = "blue";
  }
}
document.getElementById("omikuji-button").onclick = omikuji;
```

<img width="159" alt="Screenshot 2024-06-29 at 15 06 30" src="https://github.com/ut-code/utcode-starter/assets/104971044/c3eb820d-7c03-44d2-87fe-2595fc60e56e">

https://jsfiddle.net/63wv2m7r/

**Comment by chvmvd** [comment]
最終案

```html
<div id="omikuji-container">
  <div id="omikuji-description">運勢</div>
  <div id="omikuji-result">結果</div>
</div>
<button id="omikuji-button" type="button">おみくじを引く</button>
```

```css
#omikuji-container {
  font-family: serif;
  text-align: center;
  width: 80px;
  height: 180px;
  margin: 20px;
  border: double;
  border-color: red;
}

#omikuji-description {
  height: 24px;
  margin: 8px;
  font-size: 24px;
  color: red;
}

#omikuji-result {
  height: 124px;
  margin: 8px;
  font-size: 52px;
  writing-mode: vertical-rl;
}

#omikuji-button {
  width: 126px;
  height: 40px;
}
```

```js
function omikuji() {
  let r = Math.random();
  if (r < 0.2) {
    document.getElementById("omikuji-result").textContent = "大吉";
    document.getElementById("omikuji-result").style.color = "red";
  } else if (r < 0.7) {
    document.getElementById("omikuji-result").textContent = "吉";
    document.getElementById("omikuji-result").style.color = "black";
  } else {
    document.getElementById("omikuji-result").textContent = "凶";
    document.getElementById("omikuji-result").style.color = "blue";
  }
}
document.getElementById("omikuji-button").onclick = omikuji;
```

<img width="142" alt="Screenshot 2024-06-29 at 15 24 55" src="https://github.com/ut-code/utcode-starter/assets/104971044/c1435911-0f76-4da7-aeb8-b4f4b8691314">

https://jsfiddle.net/cvthp960/
